"""Recommendation model representing proposals generated by agents."""

from datetime import datetime
from enum import StrEnum
from typing import TYPE_CHECKING, Any, Dict, List, Optional
from sqlalchemy import CheckConstraint, DateTime, Float, ForeignKey, Integer, JSON, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

if TYPE_CHECKING:
    from app.models.agent_run import AgentRun
    from app.models.merchant import Merchant
    from app.models.product import Product
    from app.models.approval import Approval
    from app.models.action import Action


class RecommendationStatus(StrEnum):
    """Lifecycle status of a proposed recommendation."""
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXECUTED = "executed"
    EXPIRED = "expired"


class Recommendation(Base):
    """Proposal generated by an agent for merchant decision/approval."""

    __tablename__ = "recommendations"
    __table_args__ = (
        CheckConstraint(
            "status IN ('pending', 'approved', 'rejected', 'executed', 'expired')",
            name="chk_recommendation_status_valid",
        ),
        CheckConstraint(
            "confidence >= 0.0 AND confidence <= 1.0",
            name="chk_recommendation_confidence_range",
        ),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    agent_run_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("agent_runs.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    merchant_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("merchants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    product_id: Mapped[Optional[int]] = mapped_column(
        Integer,
        ForeignKey("products.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
    )
    recommendation_type: Mapped[str] = mapped_column(String(100), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    recommended_value: Mapped[Optional[Dict[str, Any]]] = mapped_column(JSON, nullable=True)
    confidence: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)
    status: Mapped[str] = mapped_column(
        String(50),
        default=RecommendationStatus.PENDING.value,
        nullable=False,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )

    # Relationships
    agent_run: Mapped[Optional["AgentRun"]] = relationship("AgentRun", back_populates="recommendations")
    merchant: Mapped["Merchant"] = relationship("Merchant", back_populates="recommendations")
    product: Mapped[Optional["Product"]] = relationship("Product", back_populates="recommendations")
    approvals: Mapped[List["Approval"]] = relationship(
        "Approval",
        back_populates="recommendation",
        cascade="all, delete-orphan",
    )
    actions: Mapped[List["Action"]] = relationship(
        "Action",
        back_populates="recommendation",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:
        return f"<Recommendation(id={self.id}, type='{self.recommendation_type}', status='{self.status}', confidence={self.confidence})>"
