import { useEffect,useState,type ReactNode,type FormEvent } from 'react';
import { request } from '../services/api';
export function AccountGate({children}:{children:ReactNode}) {
 const enabled=import.meta.env.PROD || import.meta.env.VITE_REQUIRE_AUTH === "true";
 const [required,setRequired]=useState<boolean|null>(enabled?null:false),[signed,setSigned]=useState(false),[signup,setSignup]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!enabled)return;let active=true;request<{required:boolean}>('/api/v1/auth/status').then(async s=>{if(!active)return;setRequired(s.required);if(sessionStorage.getItem('cartpilot-token')){try{await request('/api/v1/auth/me');if(active)setSigned(true);}catch{sessionStorage.removeItem('cartpilot-token');}}}).catch(()=>{if(active){setRequired(true);setError('Backend unavailable. Reload to retry.');}});const expired=()=>{setSigned(false);setError('Session expired. Sign in again.');};window.addEventListener('cartpilot-session-expired',expired);return()=>{active=false;window.removeEventListener('cartpilot-session-expired',expired);};},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await request<{token:string}>(`/api/v1/auth/${signup?'signup':'login'}`,undefined,{email:f.get('email'),password:f.get('password'),...(signup?{name:f.get('name'),store_name:f.get('store_name')}:{})});sessionStorage.setItem('cartpilot-token',r.token);setSigned(true);}catch(e){setError(e instanceof Error?e.message:'Sign in failed.');}finally{setBusy(false);}}
 async function logout(){try{await request('/api/v1/auth/logout',undefined,{});sessionStorage.removeItem('cartpilot-token');setSigned(false);}catch(e){setError(e instanceof Error?e.message:'Logout failed.');}}
 if(required===null)return <p role="status">Checking account access…</p>;
 if(!required||signed)return <>{signed&&<div className="card"><button className="btn secondary" onClick={logout}>Sign out</button>{error&&<p role="alert">{error}</p>}</div>}{children}</>;
 return <main style={{maxWidth:480,margin:'4rem auto',padding:24}}><h1>Welcome to CartPilot</h1><form className="card" onSubmit={submit}>{signup&&<><label>Your name<input name="name" required maxLength={255}/></label><label>Store name<input name="store_name" required maxLength={255}/></label></>}<label>Email<input name="email" type="email" autoComplete="email" required/></label><label>Password<input name="password" type="password" minLength={12} maxLength={128} autoComplete={signup?'new-password':'current-password'} required/></label><p>Use at least 12 characters.</p>{error&&<p role="alert">{error}</p>}<button className="btn" disabled={busy}>{busy?'Please wait…':signup?'Create account':'Sign in'}</button></form><button className="text-btn" onClick={()=>setSignup(!signup)}>{signup?'Sign in instead':'Create account'}</button></main>;
}
