import type { ActionPlan, PrioritizedAction } from "../types";
import { Badge, ErrorAlert } from "./common";
import { CreateAction } from "./ActionCreation";
import { PricingCard, RestockCard, PromotionCard, ListingCard } from "./recommendations/RecommendationCards";
import { percent, formatCurrency } from "../services/format";
import { goalStrategies } from "../types";
function QueueItem({ item, plan }: { item: PrioritizedAction; plan: ActionPlan }) {
 const result = plan.agent_results.find(result => result.product_id === item.product_id && result.agent_name === item.agent && result.success);
 const proposal=result?.recommendation;
 return <li className="panel priority-item"><div className="section-heading"><h3>{item.rank}. {item.product_name}</h3><Badge tone={item.priority}>{item.priority}</Badge></div><p><strong>{item.agent} · {item.action_type.replace(/_/g," ")}</strong></p>{proposal && <p>{"recommended_price" in proposal ? `${formatCurrency(proposal.current_price)} → ${formatCurrency(proposal.recommended_price)}` : "recommended_quantity" in proposal ? `${proposal.recommended_quantity} replenishment units proposed` : "promotion_recommended" in proposal ? `${proposal.discount_percentage}% temporary discount · ${formatCurrency(proposal.promotional_price)}` : `Proposed title: ${proposal.recommended_title}`}</p>}<p>{item.reason}</p><small>Confidence: {percent(item.confidence)} · Risk: {item.risk} · Strategy score: {item.priority_score.toFixed(4)}</small>{item.depends_on.length > 0 && <p>Required first: {item.depends_on.join(", ")}. Reanalyze after resolving dependencies.</p>}{item.blocked && <ErrorAlert message={item.blocked_reason || "Blocked by coordination."} />}{!item.blocked && item.approval_candidate && result?.recommendation && <CreateAction agent={item.agent} recommendation={result.recommendation} />}{!item.approval_candidate && !item.blocked && <p className="muted">Merchant verification required; no operational change can be created.</p>}</li>;
}
export function IntelligentPlan({ plan }: { plan: ActionPlan }) {
 const counts=plan.opportunity_summary;
 return <section className="intelligent-plan"><div className="panel"><p className="eyebrow">GOAL-BASED MERCHANT PLAN</p><h2>CartPilot Store Summary</h2><h3>{goalStrategies.find(strategy=>strategy.value===plan.goal)?.label??plan.goal}</h3><p>{plan.summary}</p>{counts && <div className="facts"><div><small>Inventory risks</small><strong>{counts.restock_risks.length}</strong></div><div><small>Excess / slow movers</small><strong>{counts.promotion_opportunities.length}</strong></div><div><small>Pricing opportunities</small><strong>{counts.pricing_opportunities.length}</strong></div><div><small>Listing issues</small><strong>{counts.listing_issues.length}</strong></div></div>}<p>Overall risk: <strong>{plan.overall_risk}</strong> · Confidence: {percent(plan.overall_confidence)}</p><p>Human approval required · No actions executed</p><p className="muted">{plan.selection_reason}</p></div>{!plan.complete&&<ErrorAlert message="This plan is incomplete. Review failed analyses or remaining store scope." />}{plan.warnings?.map(warning=><ErrorAlert key={warning} message={warning}/>)}
 <h2>Priority Actions</h2><ol className="priority-list" aria-label="Priority actions">{plan.prioritized_actions?.map(item=><QueueItem key={item.id} item={item} plan={plan}/>)}</ol>{!plan.prioritized_actions?.length&&<p>No operational opportunity requires action in this scope.</p>}
 <h2>Blocked Actions</h2><ul className="priority-list" aria-label="Blocked actions">{plan.blocked_actions?.map(item=><QueueItem key={item.id} item={item} plan={plan}/>)}</ul>{!plan.blocked_actions?.length&&<p>No blocked proposals.</p>}
 {(plan.omitted_actions?.length??0)>0&&<details className="panel"><summary>Additional actions outside the queue ({plan.omitted_actions!.length})</summary><ul className="priority-list">{plan.omitted_actions!.map(item=><li key={item.id}><Badge tone={item.priority}>{item.priority}</Badge> {item.product_name} · {item.agent}<p>{item.reason}</p></li>)}</ul><p>Resolve the priority queue and reanalyze to review remaining work.</p></details>}
 <h2>Conflicts, Synergies and Dependencies</h2>{plan.recommendation_relationships?.map((relationship,index)=><article key={index} className={`panel relationship ${relationship.relationship_type}`}><h3>{relationship.relationship_type} · {relationship.agent_a} ↔ {relationship.agent_b}</h3><p>Product {relationship.product_id} · {relationship.explanation}</p><p><strong>Recommended resolution:</strong> {relationship.recommended_resolution}</p></article>)}
 <details className="panel"><summary>Why each specialist ran</summary>{plan.opportunities?.map(opportunity=><section key={opportunity.product_id}><h3>{opportunity.product_name}</h3>{opportunity.selected_agents.map(agent=><p key={agent}><strong>{agent}:</strong> {opportunity.selection_reasons[agent]}</p>)}{!opportunity.selected_agents.length&&<p>No specialist was needed for the detected opportunities and goal.</p>}</section>)}</details>
 <details className="panel"><summary>Original specialist proposals ({plan.agent_results.length})</summary><p className="muted">Fresh specialist outputs are retained for review. Follow the coordinated queue and blocked decisions above.</p>{plan.agent_results.filter(result=>result.success&&result.recommendation).map(result=>{const proposal=result.recommendation!;const name=plan.opportunities?.find(o=>o.product_id===result.product_id)?.product_name;return <div key={`${result.product_id}:${result.agent_name}`}>{"recommended_title" in proposal ? <ListingCard data={proposal} name={name}/> : "promotion_recommended" in proposal ? <PromotionCard data={proposal} name={name}/> : "recommended_price" in proposal ? <PricingCard data={proposal} name={name}/> : <RestockCard data={proposal} name={name}/>}</div>;})}</details>
 {plan.agent_results.some(result=>!result.success)&&<div>{plan.agent_results.filter(result=>!result.success).map(result=><ErrorAlert key={`${result.product_id}:${result.agent_name}`} message={`${result.agent_name} · Product ${result.product_id}: ${result.error?.message}`}/>)}</div>}
 </section>;
}
