import { useState,type FormEvent } from 'react';
import { request } from '../services/api';
import { useStore } from '../hooks/useStore';
export function StoreManagement(){
 const store=useStore(),[id,setId]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const [insights,setInsights]=useState<{total_revenue:string;products:{id:number;name:string;units:number;revenue:string}[]}|null>(null);
 const [alerts,setAlerts]=useState<{product:string;message:string}[]>([]);
 const product=store.catalog?.products.find(p=>String(p.id)===id);
 async function run(operation:()=>Promise<unknown>){setBusy(true);setError('');try{await operation();setMessage("Store updated successfully.");store.refresh();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}finally{setBusy(false);}}
 function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>request(`/api/v1/products${id?'/'+id:''}`,undefined,{sku:f.get('sku'),name:f.get('name'),category:f.get('category'),description:f.get('description'),cost_price:f.get('cost_price'),selling_price:f.get('selling_price'),quantity:Number(f.get('quantity'))},id?'PUT':'POST'));}
 async function upload(file:File){try{if(file.size>200000)throw new Error('File must be under 200 KB.');const rows=(await file.text()).trim().split(/\r?\n/);if(rows.shift()!=='reference,product_id,quantity,unit_price,ordered_at')throw new Error('Use the specified CSV headers.');const sales=rows.map(row=>{const cells=row.split(',');if(cells.length!==5)throw new Error('Each row needs five fields; quoted commas are not supported.');const [reference,product_id,quantity,unit_price,ordered_at]=cells;return {reference,product_id:Number(product_id),quantity:Number(quantity),unit_price,ordered_at};});await run(()=>request('/api/v1/sales/import',undefined,{sales}));}catch(e){setError(e instanceof Error?e.message:'Invalid file.');}}
 if(!sessionStorage.getItem('cartpilot-token'))return null;
 return <section className="card"><h2>Manage your store</h2>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<label>Select product<select value={id} onChange={e=>setId(e.target.value)}><option value="">Add new product</option>{store.catalog?.products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><form key={id} onSubmit={save}>
 <label>SKU<input name="sku" required maxLength={100} defaultValue={product?.sku}/></label><label>Name<input name="name" required maxLength={255} defaultValue={product?.name}/></label><label>Category<input name="category" required maxLength={100} defaultValue={product?.category}/></label><label>Description<textarea name="description" maxLength={5000} defaultValue={product?.description||''}/></label><label>Cost<input name="cost_price" type="number" min="0" step="0.01" required defaultValue={product?.cost_price??0}/></label><label>Price<input name="selling_price" type="number" min="0.01" step="0.01" required defaultValue={product?.selling_price}/></label><label>Physical stock<input name="quantity" type="number" min="0" step="1" required defaultValue={product?.inventory?.quantity??0}/></label><button className="btn" disabled={busy}>Save product</button></form>
 {id&&<button className="btn secondary" disabled={busy} onClick={()=>{if(window.confirm('Archive product and retain order history?'))void run(()=>request(`/api/v1/products/${id}`,undefined,{},'DELETE'));}}>Archive product</button>}<h3>Import sales</h3><p>CSV headers: reference,product_id,quantity,unit_price,ordered_at. Maximum 500 rows, unique references and timezone-aware ISO dates.</p><input aria-label="Sales CSV" type="file" accept=".csv" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.target.value='';}}/>
 <button className="btn secondary" onClick={()=>void run(()=>request<NonNullable<typeof insights>>('/api/v1/analytics').then(data=>{setInsights(data);setMessage('Sales summary loaded.');}))}>Show sales ranking and revenue</button><button className="btn secondary" onClick={()=>void run(()=>request<{notifications:typeof alerts}>('/api/v1/notifications').then(data=>{setAlerts(data.notifications);setMessage('Stock alerts loaded.');}))}>Show stock alerts</button>{insights&&<div><h3>Recorded revenue: {insights.total_revenue}</h3><p>Products ranked by sold units. Recorded sales are not predicted uplift.</p><ul>{insights.products.map(p=><li key={p.id}>{p.name}: {p.units} units, revenue {p.revenue}</li>)}</ul></div>}<ul>{alerts.map((a,i)=><li key={i}>{a.product}: {a.message}</li>)}</ul></section>;
}
