import type { ListingRecommendation, PromotionRecommendation, ActionPlan, PricingRecommendation, RestockRecommendation } from "../../types";
import { formatCurrency, percent } from "../../services/format";
import { Badge, ErrorAlert } from "../common";
function Evidence({ confidence, risk }: { confidence: number; risk: string }) { return <div className="evidence"><Badge tone={risk}>Risk: {risk}</Badge><span title="Decision confidence based on available data signals; not calibrated accuracy.">Confidence: <strong>{percent(confidence)}</strong></span><span className="advisory">Recommendation Only</span></div>; }
export function PricingCard({ data, name }: { data: PricingRecommendation; name?: string }) {
  return <article className="panel recommendation"><p className="eyebrow">PRICING AGENT</p><h3>{name || `Product ${data.product_id}`}</h3><div className="price-comparison"><div><small>Current price</small><strong>{formatCurrency(data.current_price)}</strong></div><span aria-hidden="true">→</span><div><small>Recommended price</small><strong>{formatCurrency(data.recommended_price)}</strong></div><Badge>{data.price_change_percent === 0 ? "Hold Price" : `${data.price_change_percent > 0 ? "+" : ""}${data.price_change_percent}%`}</Badge></div><p>{data.reason}</p><Evidence confidence={data.confidence} risk={data.risk_level} /></article>;
}
export function RestockCard({ data, name }: { data: RestockRecommendation; name?: string }) {
  return <article className="panel recommendation"><p className="eyebrow">RESTOCK AGENT</p><h3>{name || `Product ${data.product_id}`}</h3><div className="facts"><div><small>Available inventory</small><strong>{data.available_inventory} units</strong></div><div><small>Sales velocity</small><strong>{data.sales_velocity.toFixed(2)}/day</strong></div><div><small>Days remaining</small><strong>{data.estimated_days_remaining === null ? "No recent demand" : `${data.estimated_days_remaining} days`}</strong></div><div><small>Recommended quantity</small><strong>{data.recommended_quantity} units</strong></div></div><div className="coverage"><span>Inventory coverage</span><strong>{data.estimated_days_remaining === null ? "Not forecast" : `${data.estimated_days_remaining} days of stock`}</strong><div className="coverage-track"><span style={{ width: `${data.estimated_days_remaining === null ? 0 : Math.min(100, data.estimated_days_remaining / Math.max(1, data.lead_time_days) * 100)}%` }} /></div><small>Supplier lead time: {data.lead_time_days} days · Safety stock: {data.safety_stock} units</small></div><p>{data.reason}</p><Evidence confidence={data.confidence} risk={data.risk_level} /></article>;
}
export function PromotionCard({ data, name }: { data: PromotionRecommendation; name?: string }) {
  return <article className="panel recommendation"><p className="eyebrow">PROMOTION AGENT</p><h3>{name || `Product ${data.product_id}`}</h3><Badge>{data.promotion_recommended ? `${data.discount_percentage}% Discount` : "No promotion recommended"}</Badge><div className="price-comparison"><div><small>Current price</small><strong>{formatCurrency(data.current_price)}</strong></div><span aria-hidden="true">→</span><div><small>Promotional price</small><strong>{formatCurrency(data.promotional_price)}</strong></div></div><div className="facts"><div><small>Available inventory</small><strong>{data.available_inventory} units</strong></div><div><small>Sales velocity</small><strong>{data.sales_velocity.toFixed(2)}/day</strong></div><div><small>Sales trend</small><strong>{data.sales_trend.replace(/_/g, " ")}</strong></div><div><small>Retained gross margin</small><strong>{data.retained_margin_percent.toFixed(1)}%</strong></div></div><p>{data.reason}</p><p className="muted">{data.expected_effect}</p><Evidence confidence={data.confidence} risk={data.risk_level} /></article>;
}
export function ListingCard({ data, name }: { data: ListingRecommendation; name?: string }) {
  return <article className="panel recommendation"><p className="eyebrow">LISTING AGENT</p><h3>{name || data.current_title}</h3><div className="facts"><div><small>Listing quality</small><strong>{percent(data.quality_score)}</strong></div><div><small>Category alignment</small><strong>{data.category_consistency}</strong></div></div><div className="listing-comparison"><section><h4>Current title</h4><p>{data.current_title}</p><h4>Current description</h4><p>{data.current_description || "No description recorded"}</p></section><section><h4>Recommended title</h4><p>{data.recommended_title}</p><h4>Recommended description</h4><p>{data.recommended_description}</p></section></div><h4>Issues</h4>{data.issues.length ? <ul>{data.issues.map(issue => <li key={issue}>{issue}</li>)}</ul> : <p>No major issues detected.</p>}<h4>Suggestions</h4>{data.suggestions.length ? <ul>{data.suggestions.map(suggestion => <li key={suggestion}>{suggestion}</li>)}</ul> : <p>Preserve existing factual content.</p>}{data.missing_attributes.length > 0 && <p><strong>Details to verify:</strong> {data.missing_attributes.join(", ")}</p>}{data.recommended_keywords.length > 0 && <p><strong>Existing search terms:</strong> {data.recommended_keywords.join(", ")}</p>}<p>{data.reason}</p><Evidence confidence={data.confidence} risk={data.risk_level} /></article>;
}
export function ActionPlanCard({ data, productName }: { data: ActionPlan; productName: (id: number) => string }) {
  const actions = { review_listing: "Review listing quality", review_promotion: "Review temporary promotion", no_promotion: "Hold promotion", restock: "Consider replenishment", review_inventory: "Verify inventory", review_price_change: "Review price change", hold_price: "Hold current price", monitor_inventory: "Monitor inventory" };
  return <section className="plan"><div className="panel plan-summary"><p className="eyebrow">CARTPILOT ACTION PLAN</p><h2>{data.goal}</h2><p>{data.summary}</p><Evidence confidence={data.overall_confidence} risk={data.overall_risk} /><p className="approval">{data.approval_required ? "Human approval required" : "Advisory plan"} · No actions executed</p><small>Selected agents: {data.selected_agents.join(" + ")}</small><p className="muted">{data.selection_reason}</p></div>
    {!data.complete && <ErrorAlert message="This plan is incomplete. Successful results are shown; review failed analyses before making decisions." />}
    {data.conflicts.length ? data.conflicts.map((conflict, index) => <div className="conflict" role="alert" key={index}><Badge tone={conflict.severity}>{conflict.severity} severity</Badge><h3>CONFLICT DETECTED · {productName(conflict.product_id)}</h3><p>{conflict.message}</p><strong>CartPilot recommendation</strong><p>{conflict.resolution}</p></div>) : <p className="no-conflict">No conflicts detected</p>}
    {data.relationships.map((relationship, index) => <div className="compatible" key={index}><h3>Compatible recommendations · {productName(relationship.product_id)}</h3><p>{relationship.message}</p></div>)}
    <h2 className="section-title">Recommended next steps</h2><ol className="action-list">{data.recommendations.map((item, index) => <li className="panel action-card" key={`${item.agent}-${item.product_id}`}><span className="step">{index + 1}</span><div><div className="action-heading"><Badge tone={item.priority}>Priority: {item.priority}</Badge><small>{item.agent} agent</small>{item.deferred && <Badge>Deferred</Badge>}</div><h3>{actions[item.action]} · {productName(item.product_id)}</h3><strong>{item.recommended_quantity !== null ? `${item.recommended_quantity} units proposed` : item.recommended_price !== null ? formatCurrency(item.recommended_price) : "Review required"}</strong><p>{item.coordination_reason}</p></div></li>)}</ol>
    <details className="panel"><summary>Original agent results ({data.agent_results.length})</summary><p className="muted">Original proposals are preserved below. Follow the coordinated steps above when a proposal is deferred.</p>{data.agent_results.map(result => <div key={`${result.agent_name}-${result.product_id}`}>{result.success && result.recommendation ? "recommended_title" in result.recommendation ? <ListingCard data={result.recommendation} name={productName(result.product_id)} /> : "promotion_recommended" in result.recommendation ? <PromotionCard data={result.recommendation} name={productName(result.product_id)} /> : "recommended_price" in result.recommendation ? <PricingCard data={result.recommendation} name={productName(result.product_id)} /> : <RestockCard data={result.recommendation} name={productName(result.product_id)} /> : <ErrorAlert message={`${result.agent_name} · ${productName(result.product_id)}: ${result.error?.message || "Analysis unavailable"}`} />}</div>)}</details></section>;
}
