import { fireEvent, render, screen, within } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { App } from "../src/App";
import { api } from "../src/services/api";
import type { GuardedAction } from "../src/types";
import { fetchStore, pricing, plan } from "./fixtures";
const action: GuardedAction = { id: 1, recommendation_id: 1, merchant_id: 1, product_id: 1, product_name: "Wireless Mouse", agent: "pricing", reason: "Review demand", action_type: "price_change", payload: { kind: "price_change", product_id: 1, old_price: 999, new_price: 1048.95, expected_cost: 500 }, status: "awaiting_approval", risk_level: "medium", approval_required: true, execution_mode: "local_mutation", created_at: "2026-10-03T10:00:00Z", executed_at: null, approved_by: null, approval_status: "pending", comment: null, policy: { is_valid: true, policy_name: "price", violations: [], warnings: [], requires_approval: true, risk_level: "medium" }, result: null };
describe("Guarded actions", () => {
 beforeEach(() => { window.history.replaceState({}, "", "/approvals"); global.fetch=vi.fn(fetchStore); vi.spyOn(api,"getActions").mockResolvedValue([action]); });
 it("lists scoped proposals without execution controls", async()=>{render(<App/>);expect(await screen.findByRole("button",{name:"Approve Action #1"})).toBeInTheDocument();expect(screen.getByText(/\$1,048\.95/)).toBeInTheDocument();expect(screen.queryByRole("button",{name:/Execute Approved/})).not.toBeInTheDocument();expect(api.getActions).toHaveBeenCalledWith(1,expect.any(AbortSignal));});
 it("separates approval from confirmed execution",async()=>{const review=vi.spyOn(api,"reviewAction").mockResolvedValue({...action,status:"approved"});const execute=vi.spyOn(api,"executeAction").mockResolvedValue({...action,status:"executed",result:{outcome:"executed",before:{price:"999.00"},after:{price:"1048.95"}}});render(<App/>);fireEvent.change(await screen.findByLabelText("Comment for action 1"),{target:{value:"Checked margin"}});fireEvent.click(screen.getByRole("button",{name:"Approve Action #1"}));const start=await screen.findByRole("button",{name:"Execute Approved Action #1"});expect(execute).not.toHaveBeenCalled();expect(review).toHaveBeenCalledWith(1,1,true,"Checked margin",expect.any(AbortSignal));fireEvent.click(start);fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Cancel"}));expect(execute).not.toHaveBeenCalled();fireEvent.click(start);fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Execute"}));expect(await screen.findByText("Executed Successfully")).toBeInTheDocument();expect(execute).toHaveBeenCalledTimes(1);expect(screen.queryByRole("button",{name:/Execute Approved/})).not.toBeInTheDocument();});
 it("rejects without leaving execution controls",async()=>{vi.spyOn(api,"reviewAction").mockResolvedValue({...action,status:"rejected"});render(<App/>);fireEvent.click(await screen.findByRole("button",{name:"Reject Action #1"}));await screen.findByText("rejected",{selector:"span"});expect(screen.queryByRole("button",{name:/Execute|Approve|Reject/})).not.toBeInTheDocument();});
 it("shows policy blocks",async()=>{vi.mocked(api.getActions).mockResolvedValue([{...action,status:"approved",policy:{...action.policy,is_valid:false,violations:["Current price changed since approval."]},result:{outcome:"blocked"}}]);render(<App/>);expect(await screen.findByText("Execution Blocked")).toBeInTheDocument();expect(screen.getByRole("alert")).toHaveTextContent("Current price changed");});
 it("keeps failures terminal",async()=>{vi.mocked(api.getActions).mockResolvedValue([{...action,status:"failed",result:{outcome:"failed",message:"Local execution failed."}}]);render(<App/>);expect(await screen.findByText("Execution Failed")).toBeInTheDocument();expect(screen.queryByRole("button",{name:/Execute|Approve|Reject/})).not.toBeInTheDocument();});
 it("shows execution errors in the dialog",async()=>{vi.mocked(api.getActions).mockResolvedValue([{...action,status:"approved"}]);vi.spyOn(api,"executeAction").mockRejectedValue(new Error("Action no longer approved"));render(<App/>);fireEvent.click(await screen.findByRole("button",{name:"Execute Approved Action #1"}));fireEvent.click(within(screen.getByRole("dialog")).getByRole("button",{name:"Execute"}));expect(await within(screen.getByRole("dialog")).findByRole("alert")).toHaveTextContent("no longer approved");});
 it("creates review actions from analysis",async()=>{window.history.replaceState({},"","/products");const create=vi.spyOn(api,"createAction").mockResolvedValue(action);vi.spyOn(api,"getPricingRecommendation").mockResolvedValue(pricing);render(<App/>);fireEvent.click(await screen.findByRole("button",{name:"Analyze Wireless Mouse"}));fireEvent.click(screen.getByRole("button",{name:"Run Pricing Analysis"}));fireEvent.click(await screen.findByRole("button",{name:"Create Action for Review"}));await screen.findByText(/Action #1 · awaiting approval/);expect(create).toHaveBeenCalledWith({merchant_id:1,agent:"pricing",recommendation:pricing},expect.any(AbortSignal));fireEvent.click(screen.getByRole("link",{name:"Open Approvals"}));expect(await screen.findByRole("heading",{name:"Approvals"})).toBeInTheDocument();});
 it("renders audit events and details",async()=>{window.history.replaceState({},"","/action-history");vi.spyOn(api,"getActionHistory").mockResolvedValue([{id:1,action_id:1,merchant_id:1,event_type:"execution_completed",message:"Price updated",created_at:action.created_at,metadata:{product_id:1,agent:"pricing",status:"executed",performed_by:"development-merchant",after:{price:"1048.95"}}}]);render(<App/>);expect(await screen.findByText("execution completed")).toBeInTheDocument();expect(screen.getByText(/1048.95/)).toBeInTheDocument();});
 it("prevents selecting a proposal deferred by coordination",async()=>{window.history.replaceState({},"","/ai-manager");vi.spyOn(api,"runOrchestrator").mockResolvedValue({...plan,recommendations:plan.recommendations.map(step=>({...step,deferred:true}))});render(<App/>);fireEvent.click(await screen.findByRole("checkbox"));fireEvent.click(screen.getByRole("button",{name:"Analyze with CartPilot"}));await screen.findByText("Create selected actions for review");for(const button of screen.getAllByRole("button",{name:"Create Action for Review"}))expect(button).toBeDisabled();});

});
