import { fireEvent, render, screen, within, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { App } from "../src/App";
import { api } from "../src/services/api";
import type { ActionPlan, GuardedAction, PrioritizedAction } from "../src/types";
import { fetchStore, plan } from "./fixtures";
const restock: PrioritizedAction = { id: "1:restock", rank: 1, product_id: 1, product_name: "Wireless Mouse", agent: "restock", action_type: "restock", priority: "critical", priority_score: .3, reason: "Lead-time demand exceeds inventory; safety overrides the revenue goal.", confidence: .75, risk: "high", blocked: false, blocked_reason: null, depends_on: [], approval_candidate: true };
const promotion: PrioritizedAction = { ...restock, id: "1:promotion", rank: 2, agent: "promotion", action_type: "promotion", priority: "low", blocked: true, blocked_reason: "High stockout risk blocks promotion.", depends_on: ["1:restock"], approval_candidate: false };
const intelligent: ActionPlan = { ...plan, goal: "balanced_growth", products_analyzed: 4, prioritized_actions: [restock], blocked_actions: [promotion], omitted_actions: [], warnings: [], opportunities: [{ product_id: 1, product_name: "Wireless Mouse", selected_agents: ["restock"], selection_reasons: { restock: "Replenishment protects inventory health." } }], opportunity_summary: { pricing_opportunities: [1], restock_risks: [1], promotion_opportunities: [2,3], listing_issues: [3] }, recommendation_relationships: [{ product_id: 1, agent_a: "promotion", agent_b: "restock", relationship_type: "conflict", severity: "high", explanation: "Discounts stimulate demand on constrained inventory.", recommended_resolution: "Replenish first." }, { product_id: 3, agent_a: "listing", agent_b: "promotion", relationship_type: "synergy", severity: "low", explanation: "Listing review supports promotion planning.", recommended_resolution: "Review factual information." }, { product_id: 1, agent_a: "promotion", agent_b: "restock", relationship_type: "dependency", severity: "high", explanation: "Promotion requires healthy inventory.", recommended_resolution: "Reanalyze after physical replenishment." }] };
async function analyzeStore() { await waitFor(()=>expect(screen.getByRole("button", { name: "Analyze Store" })).toBeEnabled()); fireEvent.click(screen.getByRole("button", { name: "Analyze Store" })); return screen.findByRole("heading", { name: "CartPilot Store Summary" }); }
describe("Cross-agent merchant planning", () => {
 beforeEach(()=>{window.history.replaceState({},"","/ai-manager");global.fetch=vi.fn(fetchStore);vi.spyOn(api,"runOrchestrator").mockResolvedValue(intelligent);});
 it("offers six goal cards and selects a controlled goal",async()=>{render(<App/>);await screen.findByRole("checkbox");const goal=screen.getByRole("button",{name:"Reduce Excess Inventory"});fireEvent.click(goal);expect(goal).toHaveAttribute("aria-pressed","true");expect(screen.getByLabelText("Choose a business goal")).toHaveValue("reduce_excess_inventory");await analyzeStore();expect(api.runOrchestrator).toHaveBeenCalledWith({merchant_id:1,goal:"reduce_excess_inventory",product_ids:null},expect.any(AbortSignal));});
 it("analyzes the bounded store without selecting products",async()=>{render(<App/>);await analyzeStore();expect(api.runOrchestrator).toHaveBeenCalledWith({merchant_id:1,goal:"balanced_growth",product_ids:null},expect.any(AbortSignal));expect(screen.getByRole("checkbox")).not.toBeChecked();});
 it("renders the executive summary and critical priority queue",async()=>{render(<App/>);await analyzeStore();const queue=screen.getByRole("list",{name:"Priority actions"});expect(within(queue).getByRole("heading",{name:"1. Wireless Mouse"})).toBeInTheDocument();expect(within(queue).getByText("critical")).toBeInTheDocument();expect(screen.getByText("Excess / slow movers")).toBeInTheDocument();expect(screen.getByText(/No actions executed/)).toBeInTheDocument();});
 it("explains conflicts, synergies and dependencies",async()=>{render(<App/>);await analyzeStore();for(const kind of ["conflict","synergy","dependency"])expect(screen.getByRole("heading",{name:new RegExp(`^${kind} ·`)})).toBeInTheDocument();expect(screen.getByText("Reanalyze after physical replenishment.")).toBeInTheDocument();});
 it("blocks unsafe proposals without action creation",async()=>{render(<App/>);await analyzeStore();const blocked=screen.getByRole("list",{name:"Blocked actions"});expect(within(blocked).getByRole("alert")).toHaveTextContent("High stockout risk");expect(within(blocked).queryByRole("button",{name:"Create Action for Review"})).not.toBeInTheDocument();expect(within(blocked).getByText(/Required first: 1:restock/)).toBeInTheDocument();});
 it("creates a Phase 9 review request without approving or executing",async()=>{const created: GuardedAction={id:10,recommendation_id:1,merchant_id:1,product_id:1,product_name:"Wireless Mouse",agent:"restock",reason:"Replenishment",action_type:"restock",payload:{kind:"restock",product_id:1,quantity:67},status:"awaiting_approval",risk_level:"high",approval_required:true,execution_mode:"simulated",created_at:plan.created_at,executed_at:null,approved_by:null,approval_status:"pending",comment:null,policy:{is_valid:true,policy_name:"restock_policy",violations:[],warnings:[],requires_approval:true,risk_level:"high"},result:null};const create=vi.spyOn(api,"createAction").mockResolvedValue(created);const approve=vi.spyOn(api,"reviewAction"),execute=vi.spyOn(api,"executeAction");render(<App/>);await analyzeStore();fireEvent.click(screen.getByRole("button",{name:"Create Action for Review"}));expect(await screen.findByText(/Action #10 · awaiting approval/)).toBeInTheDocument();expect(create).toHaveBeenCalledWith({merchant_id:1,agent:"restock",recommendation:plan.agent_results[1].recommendation},expect.any(AbortSignal));expect(approve).not.toHaveBeenCalled();expect(execute).not.toHaveBeenCalled();});
 it("keeps critical overflow visible with a budget warning",async()=>{vi.mocked(api.runOrchestrator).mockResolvedValue({...intelligent,omitted_actions:[{...restock,id:"2:restock",product_id:2,product_name:"Urgent Speaker"}],warnings:["Action budget: one critical item remains visible."]});render(<App/>);await analyzeStore();expect(screen.getByText(/Additional actions outside the queue \(1\)/)).toBeInTheDocument();expect(screen.getByText(/one critical item/)).toBeInTheDocument();expect(screen.getByText(/Urgent Speaker/)).toBeInTheDocument();});
 it("preserves the queue while reporting a partial failure",async()=>{vi.mocked(api.runOrchestrator).mockResolvedValue({...intelligent,complete:false,agent_results:[...intelligent.agent_results,{agent_name:"promotion",product_id:2,success:false,recommendation:null,risk_level:"high",confidence:0,error:{code:"agent_failed",message:"Promotion analysis unavailable."}}]});render(<App/>);await analyzeStore();expect(screen.getByText(/This plan is incomplete/)).toBeInTheDocument();expect(screen.getByText(/Promotion analysis unavailable/)).toBeInTheDocument();expect(screen.getByRole("list",{name:"Priority actions"})).toBeInTheDocument();});
 it("reuses equivalent session plans after repeated analysis",async()=>{render(<App/>);await analyzeStore();fireEvent.click(screen.getByRole("button",{name:"Analyze Store"}));await waitFor(()=>expect(api.runOrchestrator).toHaveBeenCalledTimes(2));fireEvent.click(screen.getByRole("link",{name:"Recommendations"}));expect(await screen.findByRole("heading",{name:"Recommendations"})).toBeInTheDocument();expect(screen.getAllByRole("heading",{name:"CartPilot Store Summary"})).toHaveLength(1);});
});
