import type { ActionPlan, Catalog, PricingRecommendation, RestockRecommendation } from "../src/types";
export const pricing: PricingRecommendation = { product_id: 1, current_price: 999, recommended_price: 1049, cost_price: 500, price_change_percent: 5, sales_velocity: 5, inventory_quantity: 8, reason: "Strong recent demand supports a moderate increase.", confidence: .86, risk_level: "medium" };
export const restock: RestockRecommendation = { product_id: 1, current_inventory: 12, available_inventory: 8, sales_velocity: 5, estimated_daily_sales: 5, estimated_days_remaining: 1.6, recommended_quantity: 67, reason: "Lead-time demand exceeds available inventory.", confidence: .75, risk_level: "high", reorder_point: 10, lead_time_days: 5, safety_stock: 10, projected_demand_during_lead_time: 25, stockout_risk: true };
export const catalog: Catalog = { products: [{ id: 1, merchant_id: 1, name: "Wireless Mouse", sku: "MOUSE-001", category: "Electronics", description: "Wireless everyday mouse", selling_price: "999.00", cost_price: "500.00", status: "active", inventory: { quantity: 12, reserved_quantity: 4, available_quantity: 8, reorder_point: 10, reorder_quantity: 40 }, sales_velocity: 5, recent_units: 70, days_remaining: 1.6, stockout_risk: true, inventory_status: "Critical", price_history: [] }], total_products: 1, low_stock_products: 1, potential_stockouts: 1, available_units: 8, recent_orders: 7, revenue: "69930.00", lookback_days: 14, as_of: "2026-10-03T10:00:00Z", has_more: false };
export const plan: ActionPlan = { merchant_id: 1, goal: "increase revenue while avoiding stockouts", summary: "Replenishment is the highest priority. Review the compatible pricing proposal.", selected_agents: ["pricing", "restock"], selection_reason: "Combined goal selects both agents.", recommendations: [{ agent: "restock", product_id: 1, priority: "critical", action: "restock", recommended_quantity: 67, recommended_price: null, deferred: false, coordination_reason: "Replenishment comes first." }, { agent: "pricing", product_id: 1, priority: "medium", action: "review_price_change", recommended_quantity: null, recommended_price: 1049, deferred: false, coordination_reason: "Monitor inventory sensitivity." }], agent_results: [{ agent_name: "pricing", product_id: 1, success: true, recommendation: pricing, confidence: pricing.confidence, risk_level: pricing.risk_level, error: null }, { agent_name: "restock", product_id: 1, success: true, recommendation: restock, confidence: restock.confidence, risk_level: restock.risk_level, error: null }], conflicts: [], relationships: [{ type: "synergy", product_id: 1, message: "Price increase and replenishment are compatible." }], overall_risk: "high", overall_confidence: .75, approval_required: true, complete: true, created_at: "2026-10-03T10:00:00Z" };
export function mockResponse(data: unknown, status = 200): Response { return new Response(JSON.stringify(data), { status, headers: { "Content-Type": "application/json" } }); }
export function fetchStore(input: RequestInfo | URL): Promise<Response> {
  const path = String(input);
  const data = path.includes("health") ? { status: "ok", database: "connected", redis: "connected" } : path.includes("merchants") ? [{ id: 1, name: "Merchant", store_name: "Demo Store" }] : path.includes("/products") ? catalog : path.includes("pricing") ? pricing : path.includes("restock") ? restock : path.includes("orchestrate") ? plan : [];
  return Promise.resolve(mockResponse(data));
}
