import { useEffect, useRef, useState } from "react";
import type { GuardedAction } from "../types";
import { useStore } from "../hooks/useStore";
import { useTask } from "../hooks/useTask";
import { api } from "../services/api";
import { formatCurrency, formatDate } from "../services/format";
import { Badge, EmptyState, ErrorAlert, Loading, PageTitle } from "../components/common";
function ProposedChange({ action }: { action: GuardedAction }) {
  const p=action.payload;
  if(p.kind==="price_change") return <p><strong>Current price:</strong> {formatCurrency(p.old_price)} → <strong>Proposed price:</strong> {formatCurrency(p.new_price)}</p>;
  if(p.kind==="restock") return <p><strong>Replenishment request:</strong> {p.quantity} units. Inventory will not increase.</p>;
  if(p.kind==="promotion") return <p><strong>Discount:</strong> {String(p.discount_percentage)}% · {formatCurrency(p.old_price)} → {formatCurrency(p.promotional_price)}. Base price will not change.</p>;
  return <div className="listing-comparison"><section><h4>Current</h4><p>{p.old_title}</p><p>{p.old_description || "No description recorded"}</p></section><section><h4>Proposed</h4><p>{p.new_title}</p><p>{p.new_description}</p></section></div>;
}
function Confirmation({ action, busy, error, cancel, execute }: { action: GuardedAction; busy: boolean; error: string | null; cancel: () => void; execute: () => void }) {
  const dialog=useRef<HTMLDivElement>(null);
  useEffect(()=>{ const previous=document.activeElement as HTMLElement|null; const overflow=document.body.style.overflow;document.body.style.overflow="hidden";dialog.current?.querySelector<HTMLButtonElement>("button")?.focus();return()=>{document.body.style.overflow=overflow;previous?.focus();};},[]);
  return <div className="drawer-backdrop confirmation-backdrop"><div className="panel confirmation" ref={dialog} role="dialog" aria-modal="true" aria-labelledby="execute-heading" onKeyDown={event=>{if(event.key==="Escape"&&!busy)cancel();if(event.key==="Tab"){const buttons=dialog.current?.querySelectorAll<HTMLButtonElement>("button:not(:disabled)");if(!buttons?.length){event.preventDefault();return;}const first=buttons[0],last=buttons[buttons.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}}}}>{error && <ErrorAlert message={error} />}<h2 id="execute-heading">Execute this approved action?</h2><p>Action #{action.id} · {action.product_name}</p><p>{action.execution_mode==="local_mutation" ? "This action will modify local/mock product data after policy revalidation." : "This action will record a simulation. No inventory arrival or base-price change will occur."}</p><p>Execution mode: <strong>{action.execution_mode.replace(/_/g," ")}</strong>. No external commerce APIs are called.</p><p>Local/Simulated · Not synchronized to Shopify.</p><div className="button-row"><button className="btn secondary" disabled={busy} onClick={cancel}>Cancel</button><button className="btn" disabled={busy} onClick={execute}>{busy?"Executing…":"Execute"}</button></div></div></div>;
}
function ActionCard({ action, busy, approve, reject, execute }: { action: GuardedAction; busy: boolean; approve: (comment:string)=>void; reject:(comment:string)=>void; execute:()=>void }) {
  const [comment,setComment]=useState("");
  return <article className="panel guarded-action"><div className="section-heading"><div><p className="eyebrow">{action.action_type.replace(/_/g," ").toUpperCase()}</p><h2>{action.product_name} · Action #{action.id}</h2></div><Badge tone={action.risk_level}>{action.status.replace(/_/g," ")}</Badge></div><p>{action.agent} agent · Risk: {action.risk_level} · Human approval required</p><Badge>{action.execution_mode==="simulated"?"Simulated action":"Local product mutation"}</Badge><ProposedChange action={action} /><p>{action.reason}</p><p>Policy check: <strong>{action.policy.is_valid?"Passed":"Blocked"}</strong></p>{!action.policy.is_valid && <ErrorAlert message={action.policy.violations.join(" ")} />}{action.status==="awaiting_approval"&&<><label>Comment for action {action.id}<textarea value={comment} maxLength={2000} onChange={event=>setComment(event.target.value)} /></label><div className="button-row"><button className="btn" disabled={busy} onClick={()=>approve(comment)}>Approve Action #{action.id}</button><button className="btn secondary" disabled={busy} onClick={()=>reject(comment)}>Reject Action #{action.id}</button></div></>}{action.status==="approved"&&<><p>Approved. Ready for execution after current-state policy checks.</p><button className="btn" disabled={busy} onClick={execute}>Execute Approved Action #{action.id}</button></>}{action.approved_by&&<p>Reviewed by {action.approved_by}{action.comment?` · ${action.comment}`:""}</p>}{action.result&&<div aria-live="polite"><h3>{action.result.outcome==="blocked"?"Execution Blocked":action.result.outcome==="failed"?"Execution Failed":"Executed Successfully"}</h3>{action.executed_at&&<p>{formatDate(action.executed_at)} · Action #{action.id}</p>}<pre className="action-result">{JSON.stringify(action.result,null,2)}</pre></div>}</article>;
}
export function Approvals() {
  const store=useStore();const [actions,setActions]=useState<GuardedAction[]>([]),[revision,setRevision]=useState(0),[status,setStatus]=useState("all"),[confirm,setConfirm]=useState<GuardedAction|null>(null),[more,setMore]=useState(false);
  const load=useTask<GuardedAction[]>(`${store.merchantId}:${revision}`),mutation=useTask<GuardedAction>(store.merchantId??"none");
  useEffect(()=>{setActions([]);setConfirm(null);if(store.merchantId)load.run(signal=>api.getActions(store.merchantId!,signal),data=>{setActions(data);setMore(data.length===100);});},[store.merchantId,revision]);
  const completed=(action:GuardedAction)=>{setActions(current=>current.map(row=>row.id===action.id?action:row));setConfirm(null);store.refresh();};
  const mutate=(action:GuardedAction,approved:boolean,comment:string)=>{if(store.merchantId)mutation.run(signal=>api.reviewAction(action.id,store.merchantId!,approved,comment,signal),completed);};
  const filtered=actions.filter(action=>status==="all"||action.status===status);
  return <>{store.error && <ErrorAlert message={store.error} />}<PageTitle title="Approvals" description="Review, approve or reject local actions. Execution is always a separate confirmed step." /><p className="development-identity">Development actor: development-merchant · Identity is not authenticated. Local/mock workflow only.</p><div className="filters"><label>Action status<select value={status} onChange={event=>setStatus(event.target.value)}>{["all","awaiting_approval","approved","rejected","executed","failed"].map(value=><option key={value} value={value}>{value.replace(/_/g," ")}</option>)}</select></label><button className="btn secondary" disabled={load.loading||mutation.loading} onClick={()=>setRevision(value=>value+1)}>Refresh actions</button></div>{load.loading&&<Loading text="Loading actions…" />}{load.error&&<ErrorAlert message={load.error} retry={()=>setRevision(value=>value+1)} />}{mutation.error&&<ErrorAlert message={mutation.error} />}{!load.loading&&!load.error&&!filtered.length&&<EmptyState>No actions match. Create an action from a recommendation first.</EmptyState>}{filtered.map(action=><ActionCard key={action.id} action={action} busy={mutation.loading} approve={comment=>mutate(action,true,comment)} reject={comment=>mutate(action,false,comment)} execute={()=>setConfirm(action)} />)}{more&&<button className="btn secondary" disabled={load.loading} onClick={()=>{if(store.merchantId)load.run(signal=>api.getActions(store.merchantId!,signal,actions.length),data=>{setActions(current=>[...current,...data]);setMore(data.length===100);});}}>Load more actions</button>}{confirm&&<Confirmation action={confirm} busy={mutation.loading} error={mutation.error} cancel={()=>setConfirm(null)} execute={()=>{if(store.merchantId)mutation.run(signal=>api.executeAction(confirm.id,store.merchantId!,signal),completed);}} />}</>;
}
