import { useState } from "react";
import { useStore } from "../hooks/useStore";
import { Badge, EmptyState, ErrorAlert, Loading, PageTitle } from "../components/common";
export function InventoryPage({ onDetails }: { onDetails: (id: number) => void }) {
  const store = useStore(); const [status, setStatus] = useState("All");
  const rows = store.catalog?.products.filter(product => status === "All" || product.inventory_status === status) ?? [];
  return <><PageTitle title="Inventory" description="Spot replenishment risk before stock becomes a constraint." />{store.loading && <Loading />}{store.error && <ErrorAlert message={store.error} retry={store.refresh} />}<label className="filter-label">Inventory status<select value={status} onChange={event => setStatus(event.target.value)}>{["All", "Healthy", "Low Stock", "Critical", "Out of Stock", "Missing", "Invalid"].map(value => <option key={value}>{value}</option>)}</select></label>
    {store.catalog && <><div className="inventory-grid">{rows.map(product => <article className="panel" key={product.id}><div className="section-heading"><Badge tone={product.inventory_status}>{product.inventory_status}</Badge><span className="muted">{product.sku}</span></div><h3>{product.name}</h3><div className="inventory-value">{product.inventory?.available_quantity ?? "—"}<small>available units</small></div><p>{product.inventory ? `${product.inventory.quantity} physical · ${product.inventory.reserved_quantity} reserved` : "Inventory record unavailable"}</p><div className="facts"><div><small>Demand</small><strong>{product.sales_velocity.toFixed(2)}/day</strong></div><div><small>Coverage</small><strong>{product.days_remaining === null ? "Not forecast" : `${product.days_remaining} days`}</strong></div></div><button className="text-btn" onClick={() => onDetails(product.id)}>View & analyze →</button></article>)}</div>{!rows.length && <EmptyState>No products in this inventory category.</EmptyState>}{store.catalog.has_more && <button className="btn secondary" disabled={store.moreLoading} onClick={store.loadMore}>Load more inventory</button>}</>}</>;
}
