import { useState } from "react";
import { useStore } from "../hooks/useStore";
import { Badge, EmptyState, ErrorAlert, Loading, PageTitle } from "../components/common";
import { ListingCard, PromotionCard, ActionPlanCard, PricingCard, RestockCard } from "../components/recommendations/RecommendationCards";
import { formatDate, percent } from "../services/format";
import { IntelligentPlan } from "../components/IntelligentPlan";
import { CreateAction, PlanActions } from "../components/ActionCreation";
export function Recommendations() {
  const store = useStore();
  const [agent, setAgent] = useState("all"), [risk, setRisk] = useState("all"), [status, setStatus] = useState("all"), [product, setProduct] = useState("");
  const name = (id: number) => store.catalog?.products.find(item => item.id === id)?.name ?? `Product ${id}`;
  const sessions = store.analyses.filter(item => (agent === "all" || item.kind === agent) && (risk === "all" || (item.kind === "orchestrator" ? item.data.overall_risk : item.data.risk_level) === risk) && (status === "all" || status === "session") && (item.kind === "orchestrator" ? item.data.recommendations.some(rec => name(rec.product_id).toLowerCase().includes(product.toLowerCase())) : name(item.data.product_id).toLowerCase().includes(product.toLowerCase())));
  const saved = store.saved.filter(item => (agent === "all" || item.agent === agent) && (risk === "all" || item.risk_level === risk) && (status === "all" || item.status === status) && (item.product_name ?? "").toLowerCase().includes(product.toLowerCase()));
  const filters: { label: string; value: string; set: (value: string) => void; options: string[] }[] = [
    { label: "Agent", value: agent, set: setAgent, options: ["all", "pricing", "restock", "promotion", "listing", "orchestrator"] },
    { label: "Risk", value: risk, set: setRisk, options: ["all", "low", "medium", "high"] },
    { label: "Status", value: status, set: setStatus, options: ["all", "session", "pending", "approved", "rejected", "executed", "expired"] },
  ];
  return <><PageTitle title="Recommendations" description="Review advisory proposals and coordinated plans without executing changes." /><div className="filters">{filters.map(filter => <label key={filter.label}>{filter.label}<select value={filter.value} onChange={event => filter.set(event.target.value)}>{filter.options.map(option => <option value={option} key={option}>{option === "all" ? "All" : option}</option>)}</select></label>)}<label>Product<input value={product} placeholder="Filter by product name…" onChange={event => setProduct(event.target.value)} /></label></div>
    <h2 className="section-title">Current session <span className="muted">· not saved to the database</span></h2>{sessions.length ? sessions.map((item, index) => <div key={`${item.created_at}-${index}`} className="session-item"><small className="muted">Analyzed {formatDate(item.created_at)}</small>{item.kind === "listing" ? <ListingCard data={item.data} name={name(item.data.product_id)} /> : item.kind === "promotion" ? <PromotionCard data={item.data} name={name(item.data.product_id)} /> : item.kind === "pricing" ? <PricingCard data={item.data} name={name(item.data.product_id)} /> : item.kind === "restock" ? <RestockCard data={item.data} name={name(item.data.product_id)} /> : item.data.goal.includes("_") ? <IntelligentPlan plan={item.data} /> : <ActionPlanCard data={item.data} productName={name} />}{item.kind === "orchestrator" ? item.data.goal.includes("_") ? null : <PlanActions plan={item.data} /> : <CreateAction agent={item.kind} recommendation={item.data} />}</div>) : <EmptyState>No session results match. Run an analysis from Products or AI Manager.</EmptyState>}
    <h2 className="section-title">Saved recommendations</h2>{store.savedLoading && <Loading text="Loading saved recommendations…" />}{store.savedError && <ErrorAlert message={store.savedError} retry={store.refresh} />}{!store.savedLoading && !store.savedError && (!saved.length ? <EmptyState>No persisted recommendations match. Analysis endpoints return proposals without saving them.</EmptyState> : saved.map(item => <article key={item.id} className="panel"><div className="section-heading"><h3>{item.title}</h3><Badge>{item.status}</Badge></div><p>{item.product_name || "Product unavailable"} · {item.agent} agent · {formatDate(item.created_at)}</p><p>{item.description}</p><div className="evidence"><Badge tone={item.risk_level ?? "unknown"}>Risk: {item.risk_level ?? "Not recorded"}</Badge><span>Confidence: {percent(item.confidence)}</span><span className="advisory">Recommendation Only</span></div>{item.payload && ("recommended_title" in item.payload ? <ListingCard data={item.payload} name={item.product_name ?? undefined} /> : "promotion_recommended" in item.payload ? <PromotionCard data={item.payload} name={item.product_name ?? undefined} /> : "recommended_price" in item.payload ? <PricingCard data={item.payload} name={item.product_name ?? undefined} /> : <RestockCard data={item.payload} name={item.product_name ?? undefined} />)}{item.payload && item.status === "pending" && <CreateAction agent={"recommended_title" in item.payload ? "listing" : "promotion_recommended" in item.payload ? "promotion" : "recommended_price" in item.payload ? "pricing" : "restock"} recommendation={item.payload} savedId={item.id} />}</article>))}</>;
}
